version: '3.8'
services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt
        volumes:
            - ${APP_DATA_DIR}/data:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8089:8080
        environment:
            - APP_HOST=zigbee2mqtt_app_1
            - APP_PORT=8089

        devices:
            # Make sure this matched your adapter location
            - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_621b6ca1d549ef11b850cd8cff00cc63-if00-port0:/dev/ttyUSB0


